### ISSUE TITLE
url化有问题吗？

### ISSUE THREAD

**Issue by ch197511161** [fxy060608/uni-cloud-router#1]

**Comment by ch197511161** [comment]
![11111](https://user-images.githubusercontent.com/26018476/99612244-2b788100-2a50-11eb-85d2-1f43a75fbfb0.png)

**Comment by ch197511161** [comment]
![11111](https://user-images.githubusercontent.com/26018476/99616836-f6246100-2a58-11eb-8e7c-4c96f56e9f3c.png)
这个样子也不行

**Comment by fxy060608** [comment]
你的url化地址不对吧
到uniCloud管理后台，云函数，详情里边，配置URL化，注意：阿里云需要带/http开头
https://unicloud.dcloud.net.cn/

![image](https://user-images.githubusercontent.com/566799/99761186-6e118a80-2b30-11eb-938e-81f7649a69ad.png)

**Comment by ch197511161** [comment]
解决了，是我自己的问题，没有配置/http,感谢！
