### ISSUE TITLE
axios提交的post请求，data中获取不到body中的数据

### ISSUE THREAD

**Issue by moohng** [fxy060608/uni-cloud-router#3]
当 `"content-type": "application/json;charset=UTF-8"` 时，处理的逻辑有问题：

https://github.com/fxy060608/uni-cloud-router/blob/0ec28fea6776a9e596f82538fe25637fee04a609/src/middleware/http.ts#L47

**Comment by fxy060608** [comment]
https://github.com/fxy060608/uni-cloud-router/commit/1924879fe5daedccd0b324b337ec023e0a71ccd5
